"""added category

Revision ID: 1f4c28365692
Revises: 90ec64b7c2e4
Create Date: 2024-05-11 07:19:54.008737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4c28365692'
down_revision = '90ec64b7c2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
