"""actually

Revision ID: ceff39aeb5fb
Revises: 1f4c28365692
Create Date: 2024-05-11 07:22:50.646892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceff39aeb5fb'
down_revision = '1f4c28365692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'category')
    # ### end Alembic commands ###
